pub mod emotional_core;
pub mod quantum_core;
pub mod language_evolution;
pub mod quantum_attention;
pub mod neural;
pub mod knowledge_graph;
pub mod inner_voice;
pub mod embryo_loop;
pub mod error_memory;
pub mod mgks_bridge;

pub use emotional_core::EmotionalCore;
pub use quantum_core::MotherQuantumCore;
pub use language_evolution::LanguageEvolutionCore;
pub use quantum_attention::QuantumAttentionMechanism;
pub use neural::NeuralNetwork;
pub use knowledge_graph::KnowledgeGraph;
pub use inner_voice::InnerVoice;
pub use embryo_loop::{EmbryoLoop, EmbryoConfig};
pub use error_memory::ErrorMemory;
pub use mgks_bridge::MGKSBridge;