pub mod embryo_loop;
pub mod emotional_core;
pub mod inner_voice;
pub mod knowledge_graph;
pub mod language_evolution;
pub mod neural;
pub mod quantum_attention;
pub mod quantum_core;
pub mod error_memory;

pub use embryo_loop::EmbryoLoop;
pub use emotional_core::EmotionalCore;
pub use inner_voice::InnerVoice;
pub use knowledge_graph::KnowledgeGraph;
pub use language_evolution::LanguageEvolution;
pub use neural::NeuralLayer;
pub use quantum_attention::QuantumAttention;
pub use quantum_core::MotherQuantumCore;
pub use error_memory::ErrorMemory;