//! AEONMI Mint — NFT metadata generator for Aeonmi artifacts
//! Produces Solana-compatible NFT metadata JSON from any compiled .ai artifact.
//! No wallet required for metadata generation — actual on-chain minting is opt-in.

use sha2::{Digest, Sha256};
use std::time::{SystemTime, UNIX_EPOCH};

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

fn sha256_hex(data: &str) -> String {
    let mut h = Sha256::new();
    h.update(data.as_bytes());
    format!("{:x}", h.finalize())
}

// ── Attribute ─────────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct NftAttribute {
    pub trait_type: String,
    pub value: String,
}

impl NftAttribute {
    pub fn new(trait_type: impl Into<String>, value: impl Into<String>) -> Self {
        Self { trait_type: trait_type.into(), value: value.into() }
    }

    pub fn to_json(&self) -> String {
        format!(
            r#"{{"trait_type":"{}","value":"{}"}}"#,
            self.trait_type, self.value
        )
    }
}

// ── Mint Metadata ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct MintMetadata {
    pub name: String,
    pub symbol: String,
    pub description: String,
    pub image: String,        // IPFS URI or placeholder
    pub animation_url: String,
    pub external_url: String,
    pub attributes: Vec<NftAttribute>,
    pub glyph_seed: String,
    pub artifact_hash: String,
    pub timestamp: u64,
}

impl MintMetadata {
    pub fn to_json(&self) -> String {
        let attrs: Vec<String> = self.attributes.iter().map(|a| a.to_json()).collect();
        format!(
            r#"{{
  "name": "{name}",
  "symbol": "{symbol}",
  "description": "{desc}",
  "image": "{image}",
  "animation_url": "{anim}",
  "external_url": "{ext}",
  "attributes": [{attrs}],
  "properties": {{
    "category": "aeonmi_artifact",
    "glyph_seed": "{glyph}",
    "artifact_hash": "{hash}",
    "timestamp": {ts},
    "creators": [],
    "files": []
  }}
}}"#,
            name = self.name,
            symbol = self.symbol,
            desc = self.description,
            image = self.image,
            anim = self.animation_url,
            ext = self.external_url,
            attrs = attrs.join(", "),
            glyph = self.glyph_seed,
            hash = self.artifact_hash,
            ts = self.timestamp,
        )
    }
}

// ── Anchor Stub ───────────────────────────────────────────────────────────────

pub struct AnchorStub {
    pub program_id: String,
    pub mint_address: String,
    pub metadata_uri: String,
}

impl AnchorStub {
    pub fn to_rust(&self) -> String {
        format!(
            r#"// Anchor mint instruction stub — generated by aeonmi mint
// Fill in: program_id, payer, mint_authority, freeze_authority
use anchor_lang::prelude::*;
declare_id!("{program_id}");

#[program]
pub mod aeonmi_mint {{
    use super::*;
    pub fn mint_artifact(ctx: Context<MintArtifact>, metadata_uri: String) -> Result<()> {{
        msg!("Minting Aeonmi artifact: {{}} -> {{}}", ctx.accounts.mint.key(), metadata_uri);
        Ok(())
    }}
}}

#[derive(Accounts)]
pub struct MintArtifact<'info> {{
    #[account(mut)]
    pub mint: Account<'info, anchor_spl::token::Mint>,
    /// CHECK: metadata account
    #[account(mut)]
    pub metadata: UncheckedAccount<'info>,
    #[account(mut)]
    pub payer: Signer<'info>,
    pub system_program: Program<'info, System>,
    pub token_program: Program<'info, anchor_spl::token::Token>,
    pub rent: Sysvar<'info, Rent>,
}}
// metadata_uri = "{metadata_uri}"
// mint_address  = "{mint_address}"
"#,
            program_id = self.program_id,
            metadata_uri = self.metadata_uri,
            mint_address = self.mint_address,
        )
    }
}

// ── Minter ────────────────────────────────────────────────────────────────────

pub struct Minter {
    pub personality: String,
}

impl Default for Minter {
    fn default() -> Self {
        Self { personality: "quantum-titan".to_string() }
    }
}

impl Minter {
    pub fn new(personality: impl Into<String>) -> Self {
        Self { personality: personality.into() }
    }

    /// Generate full NFT metadata from a `.ai` source artifact
    pub fn mint_artifact(
        &self,
        file_name: &str,
        source_content: &str,
        glyph_seed: Option<&str>,
    ) -> MintMetadata {
        let artifact_hash = sha256_hex(source_content);
        let glyph = glyph_seed.map(|s| s.to_string())
            .unwrap_or_else(|| sha256_hex(&artifact_hash)[..16].to_string());

        let clean_name = file_name
            .trim_end_matches(".ai")
            .replace(['/', '\\'], "_");

        let mut attributes = vec![
            NftAttribute::new("language", "Aeonmi"),
            NftAttribute::new("extension", ".ai"),
            NftAttribute::new("personality", &self.personality),
            NftAttribute::new("artifact_hash", &artifact_hash[..16]),
            NftAttribute::new("glyph_seed", &glyph),
            NftAttribute::new("timestamp", &now_secs().to_string()),
        ];

        // Detect quantum content
        if source_content.contains("superpose") || source_content.contains("qubit") {
            attributes.push(NftAttribute::new("contains_quantum", "true"));
        }
        if source_content.contains("quantum function") || source_content.contains("quantum circuit") {
            attributes.push(NftAttribute::new("quantum_native", "true"));
        }
        if source_content.contains("Mother") || source_content.contains("mother_ai") {
            attributes.push(NftAttribute::new("mother_linked", "true"));
        }

        MintMetadata {
            name: format!("Aeonmi Artifact: {}", clean_name),
            symbol: "AEONMI".to_string(),
            description: format!(
                "A quantum-native Aeonmi .ai artifact. Glyph-signed, UGST-rotated, Mother-linked. Hash: {}",
                &artifact_hash[..16]
            ),
            image: format!("ipfs://QmAeonmiGlyph-{}", &glyph[..8]),
            animation_url: String::new(),
            external_url: "https://aeonmi.ai".to_string(),
            attributes,
            glyph_seed: glyph,
            artifact_hash,
            timestamp: now_secs(),
        }
    }

    /// Generate Anchor stub for on-chain minting
    pub fn anchor_stub(&self, metadata: &MintMetadata) -> AnchorStub {
        let mint_address = format!("Aeonmi{}", &metadata.artifact_hash[..16]);
        AnchorStub {
            program_id: "AeonmiProgramXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX".to_string(),
            mint_address,
            metadata_uri: format!("ipfs://QmAeonmiMeta-{}", &metadata.artifact_hash[..16]),
        }
    }

    pub fn mint_and_print(&self, file_name: &str, source: &str) {
        let meta = self.mint_artifact(file_name, source, None);
        println!("{}", meta.to_json());
        let stub = self.anchor_stub(&meta);
        println!("\n// --- Anchor Stub ---");
        println!("{}", stub.to_rust());
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_basic_mint() {
        let minter = Minter::default();
        let meta = minter.mint_artifact(
            "hello.ai",
            "let x = 42; log(x);",
            None,
        );
        assert_eq!(meta.symbol, "AEONMI");
        assert!(!meta.artifact_hash.is_empty());
        let json = meta.to_json();
        assert!(json.contains("Aeonmi Artifact"));
    }

    #[test]
    fn test_quantum_detection() {
        let minter = Minter::new("quantum-titan");
        let meta = minter.mint_artifact(
            "quantum.ai",
            "qubit q; superpose(q); let r = measure(q);",
            None,
        );
        let has_quantum = meta.attributes.iter()
            .any(|a| a.trait_type == "contains_quantum" && a.value == "true");
        assert!(has_quantum);
    }

    #[test]
    fn test_anchor_stub() {
        let minter = Minter::default();
        let meta = minter.mint_artifact("test.ai", "log(1);", None);
        let stub = minter.anchor_stub(&meta);
        assert!(stub.to_rust().contains("MintArtifact"));
    }

    #[test]
    fn test_json_valid_structure() {
        let minter = Minter::default();
        let meta = minter.mint_artifact("shard.ai", "quantum function run() {}", None);
        let json = meta.to_json();
        assert!(json.contains(r#""name""#));
        assert!(json.contains(r#""symbol""#));
        assert!(json.contains(r#""attributes""#));
        assert!(json.contains("AEONMI"));
    }
}
